### ISSUE TITLE
Failure to parse Content-Type application/json in https server implementation using libmicrohttpd

### ISSUE THREAD

**Issue by vysakh-av** [Karlson2k/libmicrohttpd#21]
I am referring examples from the libmicrohttpd and for the https server implementations, in my case below is my observations and problem

- Client and server TLS connection established.
- I am sending json content payload to server
- Server failed to process the request and MHD post processor failed.
- If am tried own post processor implementation, still I can see upload_data is null and upload_data_size is 0 when process_data callback invoked when revived the POST request 
- No issue seen with raw data only problem with Json payload.

Do you have any idea about this problem or do we have any split for it.

It would be helpful if we get some help on this.

**Comment by Karlson2k** [comment]
The short and most obvious answer is that you client is failed to send the request POST body.

The track any possible problems in MHD, more info is required.

* MHD version in use?
* Which example is used and how?
* How many times response handler callback is called for every request and which values are provided for `upload_data` (`NULL` or not `NULL`) and `upload_data_size` for every call?

**Comment by Karlson2k** [comment]
Closing as not active anymore.
