### ISSUE TITLE
Clerical error in doc/examples/sessions.c

### ISSUE THREAD

**Issue by MillionSky** [Karlson2k/libmicrohttpd#23]
In master&0.9.77  doc/examples/sessions.c line 377(fill_v1_v2_form):
`    if (reply_len == snprintf(reply,
        ((size_t)reply_len) + 1,
        FORM_V1_V2,
        session->value_1,
        session->value_2))`
'==' should correct to '!='

**Comment by Karlson2k** [comment]
Thanks!
Fixed by 17b59778ea1e81b14af440fe360caef63155a910
