### ISSUE TITLE
Missing build rule for `test_websocket_browser`

### ISSUE THREAD

**Issue by zhenya4880** [Karlson2k/libmicrohttpd#25]
It seems like there is no rule for building `src/microhttpd_ws/test_websocket_browser` in appropriate `Makefile.am` file. Manually it builds (with warnings) and runs ok.

**Comment by Karlson2k** [comment]
It is intentional. 
When websockets part will be properly tested on all supported platform and fixed all portability issues, the relevant receipts will be added.
