### ISSUE TITLE
support multiple MHD_OPTION_LISTEN_SOCKET / MHD_OPTION_SOCK_ADDR in daemon

### ISSUE THREAD

**Issue by MrdUkk** [Karlson2k/libmicrohttpd#30]
currently i see only single is allowed per source code. it will be less consuming resources if daemon can listen in parallel on multiple ports/interfaces/unix domain sockets...

**Comment by Karlson2k** [comment]
Actually, not.
Right now, you can run several daemons listening on various interfaces. Idle listening daemon consumes a very small amount of resources. Most of the resources are consumed be serving connections. I would hardly notice a difference (in terms of resources) between two daemons serving 10 connections and one daemon serving 10 connections.
But if you really need to use a single daemon, you can listen by your own code on any number of interfaces and then use [`MHD_add_connection()`](https://github.com/Karlson2k/libmicrohttpd/blob/v1.0.1/src/include/microhttpd.h#L3037) to serve connections in the same daemon.

Does it solve your needs?

**Comment by Karlson2k** [comment]
Closing as inactive.
