### ISSUE TITLE
identical expression

### ISSUE THREAD

**Issue by maddin200** [Karlson2k/libmicrohttpd#31]
File:
src\microhttpd\digestauth.c  line 218

Code: 
base_algo =
    ((unsigned int) algo3)
    & ~((unsigned int)
        (MHD_DIGEST_AUTH_ALGO3_NON_SESSION // <-- identical
         | MHD_DIGEST_AUTH_ALGO3_NON_SESSION));

**Comment by Karlson2k** [comment]
Thanks, good catch!
Fixed by a00142f00480a34990298cb6d8ef299ccb19d8cd

**Comment by maddin200** [comment]
same holds for line 3570
Code:
if (0 == (((unsigned int) malgo3)
              & (MHD_DIGEST_BASE_ALGO_MD5 | MHD_DIGEST_BASE_ALGO_SHA512_256
                 | MHD_DIGEST_BASE_ALGO_SHA512_256))) // <-- identical

**Comment by Karlson2k** [comment]
Thanks!
Fixed by d94229422f07a8023dac2c32638b012b7a73b47a
