### ISSUE TITLE
Support of SSL

### ISSUE THREAD

**Issue by sridhard** [Karlson2k/libmicrohttpd#35]
Hi,

We are using microhttpd in android, ios and windows apps. We want to enable SSL support now. 
In these OSs gnutls is not very easy to build.

Does libmicrohttpd has open SSL support? is there any way that we can use openssl with libmicrohttpd?
Or is there any other way to have SSL support in android/ios and windows

Thanks

**Comment by Karlson2k** [comment]
GnuTLS works on all these platforms.
I personally regularly test GNU libmicrohttpd on Windows and macOS.

OpenSSL has licence incompatible with libmicrohttpd licence.

Next libmicrohttpd major version (in development) supports OpenSSL >= 3.0,
