### ISSUE TITLE
ios create socket for listen fail

### ISSUE THREAD

**Issue by nianxuejie** [Karlson2k/libmicrohttpd#5]
into：/* SIGPIPE disable is possible on this platform
       * (so application expect that it will be disabled),
       * but failed to be disabled here and it is not
       * possible to disable SIGPIPE by MSG_NOSIGNAL. */

The MHD_socket_create_listen_ api return MHD_INVALID_SOCKET on ios 12.4 testing when start。

Anyone and help me?

**Comment by Karlson2k** [comment]
This bug was fixed in version 0.9.71
